### ISSUE TITLE
Unable to compile on Windows 10

### ISSUE THREAD

**Issue by daryalinh** [hyperrealm/libconfig#106]
I tried to compile the latest version on Windows 10 using MinGW and MSYS.

I used `./configure` which executed fine. But `make` failed with the following error:

     CC       libconfig_la-util.lo
     In file included from util.c:27:0:
     c:\mingw\include\stdio.h:345:12: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__mingw__snprintf'
      extern int __mingw_stdio_redirect__(snprintf)(char*, size_t, const char*, ...);

Is there any way to compile libconfig in order to get the .dll libraries? I need them to link my program against it on windows.

**Comment by hyperrealm** [comment]
I haven't looked at the MinGW build in a while...it's a bit of a mess, and I just don't have the cycles for it. You could get the DLLs by building it in Visual Studio.

**Comment by jtravs** [comment]
I use https://github.com/Microsoft/vcpkg on Windows 10 to get libconfig, you could try that

**Comment by TeeEmJee** [comment]
I've got similar errors but @jtravs way worked great. I didn't know that such a tool even exists since I never developed on Windows.
The only problem I have is to link my program to the library (libconfig++.lib). I use cmake with

     find_library(CONFIG_LIBRARY config++)
     target_link_libraries(program ${CONFIG_LIBRARY})

CMake is able to find the library (I checked the path in `$CONFIG_LIBRARY` but unfortunately I still get linker errors. What's wrong? I hope my problem is not too off topic. If so I'm sorry

**Comment by keineahnung2345** [comment]
@TeeEmJee I also followed @jtravs 's suggestion, using `vcpkg` to install `libconfig` and got linker errors. It turns out that `vcpkg` by default install the x86 version for me, but I use it in x64. So after I reinstall the x64 version by `vcpkg install libconfig:x64-windows`, the problem goes away.
