### ISSUE TITLE
Regression in float_precision commit printf format

### ISSUE THREAD

**Issue by joebarker87** [hyperrealm/libconfig#81]
Commit 8471e3a changed the printf format from %g to %f. This change means that very small or very large numbers which would normally be converted into scientific notation (e.g. 1.0E10) are no longer converted. This results in a large loss of precision when writing out the config file even if the precision settings were not touched.

If I get the time this week I'll fix this and submit a pull request.

**Comment by joebarker87** [comment]
Unless I'm mistaken it seems it only needs the %.*f changing back to %.*g. The float_precision still works, even for the precision of the exponential form.

For clarity I created a gist of the patch needed: https://gist.github.com/joebarker87/0b695c3e85e07ea3caa6d707c2f3a991

**Comment by hyperrealm** [comment]
If I remember right, someone requested that change because they did not want floating point values to ever be formatted in scientific notation. So if we change it back we're likely to make someone else unhappy.

I'm open to suggestions, but probably the right solution is to make this an option so that either format can be selected.

**Comment by hyperrealm** [comment]
I made it configurable in d87d75f, via a new option.
